name:                natural-language-calculator
version:             0.1.0.0
github:              "BoeingX/natural-language-calculator"
license:             BSD3
author:              "BoeingX"
maintainer:          "user@domain.com"
copyright:           "BoeingX"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BoeingX/natural-language-calculator#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- trifecta

library:
  source-dirs: src

executables:
  natural-language-calculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - natural-language-calculator

tests:
  natural-language-calculator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - natural-language-calculator
